import { CADShape, FloorPlanTemplate } from '../types/cad';

export function getSampleHousePlan(pixelsPerMeter: number = 50): CADShape[] {
  const m = (meters: number) => meters * pixelsPerMeter;

  return [
    // 1. Teras Depan
    {
      id: 'room-teras',
      name: 'Teras Depan',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 100,
      y: 100,
      width: m(3.5),
      height: m(1.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#334155',
      strokeWidth: 2,
      opacity: 0.95,
      hatchPattern: 'tile',
      showDimensionLabels: true,
      zIndex: 1,
    },
    // 2. Ruang Tamu & Keluarga
    {
      id: 'room-living',
      name: 'R. Tamu & Keluarga',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 100,
      y: 100 + m(1.5),
      width: m(3.5),
      height: m(4.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 2,
    },
    // 3. Kamar Tidur Utama (Master Bedroom)
    {
      id: 'room-master-bed',
      name: 'Kamar Utama',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 100 + m(3.5),
      y: 100,
      width: m(3.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 3,
    },
    // 4. Kamar Tidur Anak
    {
      id: 'room-bed-2',
      name: 'Kamar Tidur 2',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 100 + m(3.5),
      y: 100 + m(3.5),
      width: m(3.5),
      height: m(3.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 4,
    },
    // 5. Dapur & Ruang Makan
    {
      id: 'room-kitchen',
      name: 'Dapur & R. Makan',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 100,
      y: 100 + m(6.0),
      width: m(4.5),
      height: m(3.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 5,
    },
    // 6. Kamar Mandi (Bathroom / WC)
    {
      id: 'room-bathroom',
      name: 'Kamar Mandi',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 100 + m(4.5),
      y: 100 + m(6.5),
      width: m(2.5),
      height: m(2.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#cffafe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 6,
    },
    // 7. Pintu Masuk Utama
    {
      id: 'door-main',
      name: 'Pintu Utama 90cm',
      type: 'door_single',
      category: 'opening',
      layer: 'DOORS',
      layerId: 'layer-openings',
      x: 100 + m(1.0),
      y: 100 + m(1.5),
      width: m(0.9),
      height: m(0.9),
      rotation: 0,
      lockAspectRatio: true,
      fillColor: '#ffffff',
      strokeColor: '#dc2626',
      strokeWidth: 2,
      opacity: 1,
      zIndex: 10,
    },
    // 8. Pintu Kamar Utama
    {
      id: 'door-master',
      name: 'Pintu Kamar',
      type: 'door_single',
      category: 'opening',
      layer: 'DOORS',
      layerId: 'layer-openings',
      x: 100 + m(3.5),
      y: 100 + m(2.0),
      width: m(0.8),
      height: m(0.8),
      rotation: 90,
      lockAspectRatio: true,
      fillColor: '#ffffff',
      strokeColor: '#dc2626',
      strokeWidth: 2,
      opacity: 1,
      zIndex: 11,
    },
    // 9. Jendela Depan
    {
      id: 'window-front',
      name: 'Jendela Depan',
      type: 'window_double',
      category: 'opening',
      layer: 'WINDOWS',
      layerId: 'layer-windows',
      x: 100 + m(2.2),
      y: 100 + m(1.5) - 6,
      width: m(1.2),
      height: 12,
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#38bdf8',
      strokeColor: '#0284c7',
      strokeWidth: 2,
      opacity: 0.9,
      zIndex: 12,
    },
    // 10. Perabot: Tempat Tidur Utama
    {
      id: 'furniture-bed',
      name: 'King Bed 180x200',
      type: 'bed_double',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: 100 + m(4.5),
      y: 100 + m(0.4),
      width: m(1.8),
      height: m(2.0),
      rotation: 0,
      lockAspectRatio: true,
      fillColor: '#f1f5f9',
      strokeColor: '#64748b',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 8,
    },
    // 11. Perabot: Sofa R. Tamu
    {
      id: 'furniture-sofa',
      name: 'Sofa 3 Seater',
      type: 'sofa_3seat',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: 100 + m(0.4),
      y: 100 + m(2.6),
      width: m(2.1),
      height: m(0.85),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e2e8f0',
      strokeColor: '#475569',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 8,
    },
    // 12. Kolom Sudut
    {
      id: 'col-1',
      name: 'Kolom 20x20',
      type: 'column_rect',
      category: 'column',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 100 - m(0.1),
      y: 100 - m(0.1),
      width: m(0.2),
      height: m(0.2),
      rotation: 0,
      lockAspectRatio: true,
      fillColor: '#1e293b',
      strokeColor: '#0f172a',
      strokeWidth: 1,
      opacity: 1,
      zIndex: 20,
    }
  ];
}

export function getSampleStudioPlan(pixelsPerMeter: number = 50): CADShape[] {
  const m = (meters: number) => meters * pixelsPerMeter;

  return [
    {
      id: 'studio-main',
      name: 'Living & Bedroom (6 x 4m)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 150,
      y: 120,
      width: m(6.0),
      height: m(4.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 1,
    },
    {
      id: 'studio-wc',
      name: 'Kamar Mandi (2 x 1.6m)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 150,
      y: 120,
      width: m(2.0),
      height: m(1.6),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#cffafe',
      strokeColor: '#0f172a',
      strokeWidth: 2,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 2,
    },
    {
      id: 'studio-kitchen',
      name: 'Kitchenette',
      type: 'kitchen_counter',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: 150 + m(2.2),
      y: 120,
      width: m(1.8),
      height: m(0.6),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#b45309',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 4,
    },
    {
      id: 'studio-bed',
      name: 'Queen Bed 160x200',
      type: 'bed_double',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: 150 + m(4.2),
      y: 120 + m(1.8),
      width: m(1.6),
      height: m(2.0),
      rotation: 0,
      lockAspectRatio: true,
      fillColor: '#f1f5f9',
      strokeColor: '#64748b',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 4,
    },
    {
      id: 'studio-balcony',
      name: 'Balkon Luar',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: 150 + m(6.0),
      y: 120 + m(1.0),
      width: m(1.2),
      height: m(2.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#334155',
      strokeWidth: 2,
      opacity: 0.9,
      showDimensionLabels: true,
      zIndex: 1,
    }
  ];
}

// 1. APARTMENT 2-BEDROOM MODERN (48 m²)
export function getApartment2BRPlan(pixelsPerMeter: number = 50): CADShape[] {
  const m = (meters: number) => meters * pixelsPerMeter;
  const startX = 120;
  const startY = 100;

  return [
    {
      id: 'apt2-living',
      name: 'Ruang Tamu & Makan',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY,
      width: m(4.5),
      height: m(4.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 1,
    },
    {
      id: 'apt2-kitchen',
      name: 'Dapur Pantry',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY + m(4.0),
      width: m(2.5),
      height: m(2.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 2,
    },
    {
      id: 'apt2-master',
      name: 'Kamar Tidur Utama',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(4.5),
      y: startY,
      width: m(3.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 3,
    },
    {
      id: 'apt2-bed2',
      name: 'Kamar Tidur 2',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(4.5),
      y: startY + m(3.5),
      width: m(3.5),
      height: m(3.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 4,
    },
    {
      id: 'apt2-bath',
      name: 'Kamar Mandi',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(2.5),
      y: startY + m(4.0),
      width: m(2.0),
      height: m(2.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#cffafe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 5,
    },
    // Furniture
    {
      id: 'apt2-bed-master',
      name: 'King Bed',
      type: 'bed_double',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: startX + m(5.5),
      y: startY + m(0.4),
      width: m(1.8),
      height: m(2.0),
      rotation: 0,
      lockAspectRatio: true,
      fillColor: '#f1f5f9',
      strokeColor: '#64748b',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 8,
    },
    {
      id: 'apt2-sofa',
      name: 'Sofa 3 Dudukan',
      type: 'sofa_3seat',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: startX + m(0.5),
      y: startY + m(1.0),
      width: m(2.1),
      height: m(0.85),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e2e8f0',
      strokeColor: '#475569',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 8,
    },
    {
      id: 'apt2-kitchen-c',
      name: 'Kitchen Set',
      type: 'kitchen_counter',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: startX + m(0.1),
      y: startY + m(4.2),
      width: m(2.3),
      height: m(0.6),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#b45309',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 8,
    },
    // Doors
    {
      id: 'apt2-door-main',
      name: 'Pintu Masuk',
      type: 'door_single',
      category: 'opening',
      layer: 'DOORS',
      layerId: 'layer-openings',
      x: startX + m(0.2),
      y: startY,
      width: m(0.9),
      height: m(0.9),
      rotation: 0,
      lockAspectRatio: true,
      fillColor: '#ffffff',
      strokeColor: '#dc2626',
      strokeWidth: 2,
      opacity: 1,
      zIndex: 10,
    }
  ];
}

// 2. RUMAH TROPIS KELUARGA TIPE 70 (70 m²)
export function getHouseType70Plan(pixelsPerMeter: number = 50): CADShape[] {
  const m = (meters: number) => meters * pixelsPerMeter;
  const startX = 80;
  const startY = 80;

  return [
    {
      id: 'h70-foyer',
      name: 'Teras & Foyer',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY,
      width: m(3.5),
      height: m(2.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#0f172a',
      strokeWidth: 2,
      opacity: 1,
      hatchPattern: 'tile',
      showDimensionLabels: true,
      zIndex: 1,
    },
    {
      id: 'h70-living',
      name: 'R. Tamu & Keluarga Luas',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY + m(2.0),
      width: m(4.5),
      height: m(4.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 2,
    },
    {
      id: 'h70-dining',
      name: 'R. Makan & Dapur Bersih',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY + m(6.5),
      width: m(4.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 3,
    },
    {
      id: 'h70-master',
      name: 'Kamar Utama (En-Suite)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(4.5),
      y: startY,
      width: m(4.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 4,
    },
    {
      id: 'h70-bed2',
      name: 'Kamar Tidur 2',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(4.5),
      y: startY + m(3.5),
      width: m(3.5),
      height: m(3.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 5,
    },
    {
      id: 'h70-bed3',
      name: 'Kamar Tidur 3',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(4.5),
      y: startY + m(6.5),
      width: m(3.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 6,
    },
    {
      id: 'h70-bath',
      name: 'KM / WC Keluarga',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(8.0),
      y: startY + m(3.5),
      width: m(2.0),
      height: m(2.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#cffafe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 7,
    },
    // Dining table
    {
      id: 'h70-dt',
      name: 'Meja Makan 6 Kursi',
      type: 'dining_table',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: startX + m(1.0),
      y: startY + m(7.2),
      width: m(1.6),
      height: m(0.9),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#475569',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 10,
    }
  ];
}

// 3. KANTOR STARTUP & TECH OFFICE (100 m²)
export function getOfficeTechPlan(pixelsPerMeter: number = 50): CADShape[] {
  const m = (meters: number) => meters * pixelsPerMeter;
  const startX = 80;
  const startY = 80;

  return [
    {
      id: 'off-open',
      name: 'Open Plan Workstation (12 Pax)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY,
      width: m(7.5),
      height: m(5.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 1,
    },
    {
      id: 'off-meeting',
      name: 'Ruang Rapat Utama (10 Pax)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(7.5),
      y: startY,
      width: m(4.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 2,
    },
    {
      id: 'off-director',
      name: 'Ruang Direktur / Manager',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(7.5),
      y: startY + m(3.5),
      width: m(4.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 3,
    },
    {
      id: 'off-reception',
      name: 'Resepsionis & Lounge Tamu',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY + m(5.5),
      width: m(4.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 4,
    },
    {
      id: 'off-pantry',
      name: 'Pantry & Coffee Corner',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(4.5),
      y: startY + m(5.5),
      width: m(3.0),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 5,
    },
    {
      id: 'off-toilet',
      name: 'Toilet Karyawan',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(7.5),
      y: startY + m(7.0),
      width: m(4.5),
      height: m(2.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#cffafe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 6,
    },
    // Conference table
    {
      id: 'off-conf-table',
      name: 'Meja Rapat Konferensi',
      type: 'dining_table',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: startX + m(8.5),
      y: startY + m(1.0),
      width: m(2.5),
      height: m(1.2),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#334155',
      strokeWidth: 2,
      opacity: 0.9,
      zIndex: 9,
    }
  ];
}

// 4. COWORKING HUB & MEETING BOOTHS (75 m²)
export function getOfficeCoworkingPlan(pixelsPerMeter: number = 50): CADShape[] {
  const m = (meters: number) => meters * pixelsPerMeter;
  const startX = 100;
  const startY = 90;

  return [
    {
      id: 'cw-communal',
      name: 'Communal Work Tables',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY,
      width: m(6.0),
      height: m(5.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 1,
    },
    {
      id: 'cw-focus',
      name: 'Focus Pods (Bilik Privat)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(6.0),
      y: startY,
      width: m(3.5),
      height: m(2.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 2,
    },
    {
      id: 'cw-meet',
      name: 'Meeting Pod 6p',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(6.0),
      y: startY + m(2.5),
      width: m(3.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 3,
    },
    {
      id: 'cw-lounge',
      name: 'Cafe & Breakout Lounge',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY + m(5.0),
      width: m(6.0),
      height: m(3.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 4,
    }
  ];
}

// 5. KAFE & COFFEE SHOP MODERN (60 m²)
export function getCommercialCoffeePlan(pixelsPerMeter: number = 50): CADShape[] {
  const m = (meters: number) => meters * pixelsPerMeter;
  const startX = 90;
  const startY = 80;

  return [
    {
      id: 'cafe-seating',
      name: 'Area Duduk Pelanggan (Indoor)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY,
      width: m(6.5),
      height: m(4.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 1,
    },
    {
      id: 'cafe-bar',
      name: 'Espresso Bar & Kasir POS',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(6.5),
      y: startY,
      width: m(3.5),
      height: m(3.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#b45309',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 2,
    },
    {
      id: 'cafe-kitchen',
      name: 'Kitchen Prep & Gudang',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(6.5),
      y: startY + m(3.0),
      width: m(3.5),
      height: m(3.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 3,
    },
    {
      id: 'cafe-outdoor',
      name: 'Deck Outdoor Terrace',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY + m(4.5),
      width: m(4.5),
      height: m(2.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#334155',
      strokeWidth: 2,
      opacity: 0.9,
      hatchPattern: 'wood',
      showDimensionLabels: true,
      zIndex: 4,
    },
    {
      id: 'cafe-wc',
      name: 'Toilet Tamu',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(4.5),
      y: startY + m(4.5),
      width: m(2.0),
      height: m(2.5),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#cffafe',
      strokeColor: '#0f172a',
      strokeWidth: 2,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 5,
    },
    // Espresso Counter table
    {
      id: 'cafe-counter-fur',
      name: 'Meja Barista',
      type: 'kitchen_counter',
      category: 'furniture',
      layer: 'FURNITURE',
      layerId: 'layer-furniture',
      x: startX + m(6.7),
      y: startY + m(0.4),
      width: m(3.0),
      height: m(0.7),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#b45309',
      strokeWidth: 1.5,
      opacity: 0.9,
      zIndex: 8,
    }
  ];
}

// 6. BUTIK FASHION & RETAIL STORE (50 m²)
export function getCommercialBoutiquePlan(pixelsPerMeter: number = 50): CADShape[] {
  const m = (meters: number) => meters * pixelsPerMeter;
  const startX = 100;
  const startY = 80;

  return [
    {
      id: 'btq-display',
      name: 'Area Display & Rak Pakaian Utama',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY,
      width: m(5.5),
      height: m(5.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f8fafc',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 1,
    },
    {
      id: 'btq-fitting',
      name: 'Kamar Pas (Fitting Rooms)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(5.5),
      y: startY,
      width: m(2.5),
      height: m(2.2),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#0f172a',
      strokeWidth: 2.5,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 2,
    },
    {
      id: 'btq-storage',
      name: 'Gudang Stok Barang',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(5.5),
      y: startY + m(2.2),
      width: m(2.5),
      height: m(2.8),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#f1f5f9',
      strokeColor: '#0f172a',
      strokeWidth: 3,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 3,
    },
    {
      id: 'btq-cashier',
      name: 'Meja Kasir POS & Wrapping',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX,
      y: startY + m(5.0),
      width: m(3.5),
      height: m(2.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#fef3c7',
      strokeColor: '#0f172a',
      strokeWidth: 2.5,
      opacity: 1,
      showDimensionLabels: true,
      zIndex: 4,
    },
    {
      id: 'btq-showcase',
      name: 'Etalase Kaca Depan (Window Display)',
      type: 'rect_room',
      category: 'room',
      layer: 'WALLS',
      layerId: 'layer-walls',
      x: startX + m(3.5),
      y: startY + m(5.0),
      width: m(4.5),
      height: m(2.0),
      rotation: 0,
      lockAspectRatio: false,
      fillColor: '#e0f2fe',
      strokeColor: '#0284c7',
      strokeWidth: 2,
      opacity: 0.9,
      showDimensionLabels: true,
      zIndex: 5,
    }
  ];
}

// Master Template Catalog
export const FLOOR_PLAN_TEMPLATES: FloorPlanTemplate[] = [
  // Apartemen
  {
    id: 'apt-studio-24',
    title: 'Studio Apartemen Compact',
    category: 'apartment',
    categoryLabel: 'Apartemen',
    areaM2: 24,
    dimensions: '6.0 × 4.0 m',
    roomCount: 4,
    description: 'Tata letak studio modern efisien dengan area tidur serbaguna, kitchenette, kamar mandi, dan balkon.',
    features: ['Kitchenette Dapur', 'Balkon Luar', 'Kamar Mandi 2x1.6m', 'Queen Bed Serbaguna'],
    shapes: getSampleStudioPlan(50),
    badge: 'Populer',
  },
  {
    id: 'apt-2br-48',
    title: 'Apartemen 2-Bedroom Modern',
    category: 'apartment',
    categoryLabel: 'Apartemen',
    areaM2: 48,
    dimensions: '8.0 × 6.5 m',
    roomCount: 5,
    description: 'Unit apartemen 2 kamar tidur lengkap dengan ruang tamu terbuka, dapur pantry, kamar mandi, dan kamar anak.',
    features: ['Kamar Tidur Utama', 'Kamar Tidur Anak', 'Dapur Pantry Bersih', 'Ruang Tamu Terbuka'],
    shapes: getApartment2BRPlan(50),
    badge: 'Keluarga Muda',
  },

  // Rumah Tinggal
  {
    id: 'house-type-36',
    title: 'Rumah Minimalis Tipe 36/60',
    category: 'house',
    categoryLabel: 'Rumah Tinggal',
    areaM2: 36,
    dimensions: '7.0 × 6.0 m',
    roomCount: 6,
    description: 'Denah rumah tinggal minimalis favorit Indonesia dengan 2 kamar tidur, ruang keluarga, dapur belakang, dan teras.',
    features: ['2 Kamar Tidur', 'Ruang Tamu & Keluarga', 'Dapur & R. Makan', 'Teras Depan'],
    shapes: getSampleHousePlan(50),
    badge: 'Standar Indonesia',
  },
  {
    id: 'house-type-70',
    title: 'Rumah Keluarga Tropis Tipe 70',
    category: 'house',
    categoryLabel: 'Rumah Tinggal',
    areaM2: 70,
    dimensions: '10.0 × 8.0 m',
    roomCount: 7,
    description: 'Rumah tinggal keluarga luas dengan 3 kamar tidur (termasuk master en-suite), ruang makan luas, dan foyer teras.',
    features: ['3 Kamar Tidur', 'Master Bedroom En-Suite', 'Ruang Keluarga Luas', 'Dapur Bersih & R. Makan'],
    shapes: getHouseType70Plan(50),
    badge: 'Lengkap',
  },

  // Kantor & Workspace
  {
    id: 'office-tech-100',
    title: 'Open-Plan Tech Office (100 m²)',
    category: 'office',
    categoryLabel: 'Kantor & Kerja',
    areaM2: 100,
    dimensions: '12.0 × 8.5 m',
    roomCount: 6,
    description: 'Tata letak kantor startup modern dengan open workstation 12 orang, ruang rapat 10 pax, ruang manajer, dan lounge pantry.',
    features: ['Workstation 12 Pax', 'Ruang Rapat 10 Pax', 'Ruang Direktur', 'Pantry & Coffee Breakout'],
    shapes: getOfficeTechPlan(50),
    badge: 'Startup Tech',
  },
  {
    id: 'office-coworking-75',
    title: 'Coworking Hub & Meeting Pods',
    category: 'office',
    categoryLabel: 'Kantor & Kerja',
    areaM2: 75,
    dimensions: '9.5 × 8.0 m',
    roomCount: 4,
    description: 'Ruang kerja kolaboratif dengan communal tables, bilik fokus privat (phone booths), mini conference, dan lounge santai.',
    features: ['Communal Tables', 'Focus Pods', 'Meeting Pod', 'Cafe Lounge'],
    shapes: getOfficeCoworkingPlan(50),
  },

  // Komersial & Retail
  {
    id: 'commercial-coffee-60',
    title: 'Kafe & Coffee Shop Kekinian',
    category: 'commercial',
    categoryLabel: 'Ruang Komersial',
    areaM2: 60,
    dimensions: '10.0 × 6.5 m',
    roomCount: 5,
    description: 'Denah kafe modern dengan bar espresso dan kasir POS, area duduk indoor, outdoor terrace deck, dan kitchen prep.',
    features: ['Espresso Bar & Kasir', 'Seating Indoor Luas', 'Outdoor Wood Deck', 'Kitchen Prep & Gudang'],
    shapes: getCommercialCoffeePlan(50),
    badge: 'F&B Cafe',
  },
  {
    id: 'commercial-boutique-50',
    title: 'Butik Fashion & Retail Store',
    category: 'commercial',
    categoryLabel: 'Ruang Komersial',
    areaM2: 50,
    dimensions: '8.0 × 6.5 m',
    roomCount: 5,
    description: 'Tata letak toko pakaian / retail butik dengan etalase jendela display, display rak baju, kasir POS, dan kamar pas.',
    features: ['Etalase Jendela Display', 'Rak Display Baju', '2 Bilik Kamar Pas', 'Gudang Stok Barang'],
    shapes: getCommercialBoutiquePlan(50),
    badge: 'Toko Retail',
  },
];
